Repository ArkEcosystem/docs-deployer, pull requests merged in 2019-09, with the labels that each got.

#8 docs: add update your bridgechain page
  docs/deploy/getting-started.md
  docs/deploy/security-notice.md
  docs/deploy/updating-your-bridgechain.md
  website/sidebars.json
Labels: Complexity: Medium

#6 Avfcpieface peer update docs
  docs/customize/devnet-peers.md
  docs/customize/mainnet-peers.md
Labels: Complexity: Low, Status: Contributor Approved

#9 docs: add snapshot step to updating-your-bridgechain
  docs/deploy/updating-your-bridgechain.md
Labels: Complexity: Low, Type: Documentation
